# Generated by Django 5.0.6 on 2024-05-26 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_mobile_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='business_number',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='direct_number',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
