# Generated by Django 5.0.6 on 2024-05-28 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_payment_payment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reg_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
