# Generated by Django 5.0.6 on 2024-06-03 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_payment_tax_alter_user_mobile_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='membership_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
