# Generated by Django 5.0.6 on 2024-06-20 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_userprofile_membership_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('Internal', 'Internal'), ('Client', 'Client'), ('Delegate', 'Delegate'), ('VIP', 'VIP'), ('Speaker', 'Speaker'), ('Sponsor', 'Sponsor'), ('Exhibitor', 'Exhibitor'), ('Media', 'Media'), ('Crew', 'Crew'), ('Diplomat', 'Diplomat'), ('Vendor', 'Vendor'), ('Team', 'Team'), ('Executive Committee Member', 'Executive Committee Member'), ('Director', 'Director'), ('Chairman', 'Chairman'), ('Honorary Secretary', 'Honorary Secretary'), ('Vice Chairman', 'Vice Chairman')], default='Internal', max_length=255),
        ),
    ]
