# Generated by Django 5.0.6 on 2024-08-01 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_user_user_type'),
    ]
    #
    # operations = [
    #     migrations.AlterField(
    #         model_name='user',
    #         name='password',
    #         field=models.CharField(max_length=128, verbose_name='password'),
    #     ),
    # ]
