# Generated by Django 5.0.6 on 2024-08-04 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('Admin', 'Admin'), ('OFFSITE', 'OFFSITE')], max_length=255, null=True),
        ),
    ]
